### ISSUE TITLE
Add Early Return in useEffect for Cache Existence Check

### ISSUE THREAD

**Issue by Slacky300** [AdityaShah7867/React-Native-Gallery-With-Caching#1]
<div>
<img width="361" alt="image" src="https://github.com/AdityaShah7867/React-Native-Gallery-With-Caching/assets/98531038/eb65fc46-790f-4c7e-8d33-70e3d2216790">
</div>
@AdityaShah7867 in screens/HomeScreen.js on line no. 17 consider adding an early return statement just after the execution of `setPhotos`. This can lead to an early exit and reduce unnecessary function computation, especially when the data is already available in the cache.

**Comment by AdityaShah7867** [comment]
Return statement is not written beacause i need to call api after the cached images are load to load new images when user is online

**Comment by Slacky300** [comment]
Yeah understand now, Thanks  for the clarification
